[package]
name = "live-activity"
version = "0.1.0"
authors = [ "You" ]
description = ""
edition = "2021"
rust-version = "1.77.2"
exclude = ["/examples", "/dist-js", "/guest-js", "/node_modules"]
links = "live-activity"

[dependencies]
tauri = { version = "2.9.2" }
serde = "1.0"
thiserror = "2"
anyhow = "1"
corelib = { path = "../../modules/core" }

[target.'cfg(windows)'.dependencies.win-toast-notify]
version = "0.1.6"

[target.'cfg(target_os = "macos")'.dependencies]
mac-notification-sys = "0.6.8"

[build-dependencies]
tauri-plugin = { version = "2.5.1", features = ["build"] }
